---
# file: roles/ui/tasks/programs.yml
- debug: msg="bits {{ ansible_userspace_bits }}"

- name: download telegram 32
  get_url: url=https://tdesktop.com/linux32 dest=/root 
  register: download_result
  when: ansible_userspace_bits == "32" 

- name: download telegram 64
  get_url: url=https://tdesktop.com/linux dest=/root/tsetup.0.7.9.tar.xz
  register: download_result
  when: ansible_userspace_bits == "64" 

- debug: msg="downloaded {{ download_result.dest }}"

- name: unpack telegram
  unarchive: src={{ download_result.dest }} dest=/opt/ creates=/opt/Telegram

- name: link telegram binary
#  command: ln -sf /opt/Telegram/Telegram /usr/bin/telegram creates=/usr/bin/telegram
  file: src=/opt/Telegram/Telegram dest=/usr/bin/telegram state=link

- name: ensure java7
  pacman: name=jdk7-openjdk state=present

- name: ensure java8
  pacman: name=jdk8-openjdk state=present

- name: download intellij
  get_url: url=http://download-cf.jetbrains.com/idea/ideaIU-14.0.2.tar.gz dest=/root/ideaIU-14.0.2.tar.gz
  register: download_result_intellij

- debug: msg="downloaded {{ download_result_intellij.dest }}"

- name: unpack intellij
  unarchive: src={{ download_result_intellij.dest }} dest=/opt/ creates=/opt/idea-IU-139.659.2

- name: download wmname
  get_url: url=http://dl.suckless.org/tools/wmname-0.1.tar.gz dest=/root/wmname-0.1.tar.gz
  register: result_wmname

- name: unpack wmname
  unarchive: src={{ result_wmname.dest }} dest=/root/ creates=/root/wmname-0.1

- name: install wmname
  command: "{{ item }}" 
  args:
    chdir: /root/wmname-0.1
    creates: /usr/local/bin/wmname
  with_items:
    - make
    - make install

- name: install idea.sh
  copy: src=idea.sh dest=/opt/idea-IU-139.659.2/bin/idea.sh mode=0755

- name: link intellij binary to main
  file: src=/opt/idea-IU-139.659.2/ dest=/opt/idea state=link

- name: link usr bin to intellij
  file: src=/opt/idea/bin/idea.sh dest=/usr/bin/intellij state=link
