---
# file: roles/base/tasks/main.yml

- name: Ensure latest python2 is installed
  raw: pacman -S python2 --noconfirm --needed
  tags: raw

- name: Add ansible-server key to authorized_keys
  authorized_key: key="{{ ansible_server_public_key }}" manage_dir=yes state=present user=root

- name: timesyncd config
  copy: src=timesyncd.conf dest=/etc/systemd/timesyncd.conf mode=0644

- name: start timesyncd service
  service: name=systemd-timesyncd.service state=started enabled=yes 

- name: set uk keyboard layout
  command: localectl set-keymap --no-convert uk creates=/etc/vconsole.conf

- name: ensure touchpad drivers
  pacman: name=xf86-input-synaptics state=present

- name: copy touchpad config to etc
  copy: src=/usr/share/X11/xorg.conf.d/50-synaptics.conf dest=/etc/X11/xorg.conf.d/50-synaptics.conf

- include: core_packages.yml
- include: user_kyle.yml

