---
# file: roles/base/tasks/user_kyle.yml

- name: ensure user kyle
  user: generate_ssh_key=yes name=kyle shell=/usr/bin/fish state=present password="$6$rounds=100000$L1GLMUC43Ja0kUOg$CDSkgblCw5HwK5GTcvcAvoj5iaWffeK3NYMEMgkqd4dcAGeoOfAiGn3LK9Q/lfQ363/R2LuD7/vnge79cgRkN1"
