---
# file: roles/base/tasks/cli_utils.yml

- name: ensure fish
  pacman: name=fish state=present

- name: ensure tmux
  pacman: name=tmux state=present

- name: tmux config
  copy: src=tmux.conf dest=/etc/tmux.conf mode=0755

- name: switch root to fish
  user: name=root shell=/usr/bin/fish

- name: install fish config
  copy: src=config.fish dest={{ item }}
  with_items:
    - /root/.config/fish/config.fish
    - /home/kyle/.config/fish/config.fish

- name: ensure lynx
  pacman: name=lynx state=present

- name: ensure vim
  pacman: name=vim state=present

- name: ensure xterm
  pacman: name=xterm state=present

- name: xterm config
  copy: src=Xdefaults dest=/home/kyle/.Xdefaults mode=0755
